### ISSUE TITLE
After crash: start not possible

### ISSUE THREAD

**Issue by mdrenger** [snapcrafters/tmnationsforever#12]
i exited an online game and tmnf crashed. Since then i am not able to restart the game.

$: tmnationsforever
X Error:  BadWindow
  Request Major code 1 ()
  ResourceID 0x2600005
  Error Serial #9
  Current Serial #13

platform: ubuntu with i3
Linux version 4.15.0-23-generic (buildd@lgw01-amd64-055) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))

**Comment by MarkoIndaco** [comment]
Same here:

X Error:  BadWindow
  Request Major code 1 ()
  ResourceID 0x7800005
  Error Serial #9
  Current Serial #13

Linux Mint 19.1 Cinnamon (64-bit)
Kernel 5.3.0-24-generic
nVidia GeForce 9500 GT

It was working fine since yesterday (never connected online). The only thing I remember is that I was unlocked all the races from the first 3 color levels.

**Comment by galgalesh** [comment]
I think this issue is fixed with the refactor we did in July 2020. Closing it for now. Please reopen if the problem returns again.
