### ISSUE TITLE
Use a dialogue rather than a notification

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/tmnationsforever#6]
I got a notification about the fact that it's a Wine snap (great idea btw!) but I can't read the full notification because there's not enough space in the notification box to see it. Maybe a dialogue box would be a better approach... also [looking at the OMG! article](https://www.omgubuntu.co.uk/2018/06/trackmania-nations-forever-ubuntu-snap?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+d0od+%28OMG%21+Ubuntu%21%29), does this notification only come up for those refreshing from revisions which didn't have the dialogue? I don't see why it should come up otherwise, since there's a dialogue on install...

![screenshot from 2018-06-16 11-55-41](https://user-images.githubusercontent.com/3178485/41498105-cb887f6a-715c-11e8-8aa3-fb55484b7535.png)

Further, the dialogue given in OMG! incorrectly capitalizes 'snapcrafters' in the URL and that link doesn't look like a clickable link?

**Comment by xordspar0** [comment]
Since the dialog shows on the first run during installation, maybe it's not necessary to show a notification at all when the app starts. Otherwise, it would be easy to show a splash dialog with a timeout just like the first run.

**Comment by xordspar0** [comment]
That notification is gone in the latest version.

**Comment by galgalesh** [comment]
The notification is indeed gone in the latest version. The store description makes it clear this snap uses Wine to run a Windows application. I don't think showing a warning in a splash dialog adds much since the app works well enough for me to lose a significant amount of time getting almost all medals without any crash. The only bugs I experienced were also present when you run the app on Windows.
